name: domus-documents
version: "3.4"
services:
  app:
    container_name: domus-documents
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - target: 8000
        published: 8010
        protocol: tcp
    healthcheck:
      test:
        ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - type: bind
        source: /DATA/AppData/paperless/data
        target: /usr/src/paperless/data
      - type: bind
        source: /DATA/Media/Documents
        target: /usr/src/paperless/media
      - type: bind
        source: /DATA/AppData/paperless/export
        target: /usr/src/paperless/export
      - type: bind
        source: /DATA/AppData/paperless/consume
        target: /usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      # The UID and GID of the user used to run paperless in the container. Set this
      # to your UID and GID on the host so that you have write access to the
      # consumption directory.
      USERMAP_UID: $PUID
      USERMAP_GID: $PGID
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/paperless/redisdata
        target: /data

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/paperless/pgdata
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
# Additional languages to install for text recognition, separated by a
# whitespace. Note that this is
# different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
# language used for OCR.
# The container installs English, German, Italian, Spanish and French by
# default.
# See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
# for available languages.
#PAPERLESS_OCR_LANGUAGES: tur ces
# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
#PAPERLESS_SECRET_KEY: change-me
# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
#PAPERLESS_TIME_ZONE: America/Los_Angeles
# The default language to use for OCR. Set this to the language most of your
# documents are written in.
#PAPERLESS_OCR_LANGUAGE: eng
