name: domus-media
version: "3"
services:
  app:
    container_name: domus-media
    image: linuxserver/plex:1.32.7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VERSION: ""
      PLEX_CLAIM: ""
    volumes:
      - type: bind
        source: /DATA/AppData/plex/config
        target: /config
      - type: bind
        source: /DATA/Media/Music
        target: /music
      - type: bind
        source: /DATA/Media/TV Shows
        target: /tv
      - type: bind
        source: /DATA/Media/Movies
        target: /movies
      - type: bind
        source: /DATA/Media/Videos
        target: /videos
    ports:
      - target: 32400
        published: 32400
        protocol: tcp
      - target: 3005
        published: 3005
        protocol: tcp
      - target: 8324
        published: 8324
        protocol: tcp
      - target: 32469
        published: 32469
        protocol: tcp
      - target: 1900
        published: 1900
        protocol: udp
      - target: 32410
        published: 32410
        protocol: udp
      - target: 32412
        published: 32412
        protocol: udp
      - target: 32413
        published: 32413
        protocol: udp
      - target: 32414
        published: 32414
        protocol: udp
    x-domus:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: VERSION
          description:
            en_us: Set whether to update plex or not - see Application Setup section.
        - container: PLEX_CLAIM
          description:
            en_us: Optionally you can obtain a claim token from https://plex.tv/claim and input here. Keep in mind that the claim tokens expire within 4 minutes.
      volumes:
        - container: /config
          description:
            en_us: Appdata
        - container: /music
          description:
            en_us: Music - /music
        - container: /tv
          description:
            en_us: TV - /tv
        - container: /movies
          description:
            en_us: Movies - /movies
        - container: /videos
          description:
            en_us: Videos - /videos
      ports:
        - container: "32400"
          description:
            en_us: For access to the Plex Media Server Webui (No effect in host mode - reference only)
        - container: "3005"
          description:
            en_us: For controlling Plex Home Theater via Plex Companion (No effect in host mode - reference only)
        - container: "8324"
          description:
            en_us: For controlling Plex for Roku via Plex Companion (No effect in host mode - reference only)
        - container: "32469"
          description:
            en_us: For access to the Plex DLNA Server (No effect in host mode - reference only)
        - container: "1900"
          description:
            en_us: For access to the Plex DLNA Server (No effect in host mode - reference only)
        - container: "32410"
          description:
            en_us: For current GDM network discovery (No effect in host mode - reference only)
        - container: "32412"
          description:
            en_us: For current GDM network discovery (No effect in host mode - reference only)
        - container: "32413"
          description:
            en_us: For current GDM network discovery (No effect in host mode - reference only)
        - container: "32414"
          description:
            en_us: For current GDM network discovery (No effect in host mode - reference only)

x-domus:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: "Visit homepage: https://hub.docker.com/r/linuxserver/plex/"
  tagline:
    en_us: Organizes video, music and photos from personal media libraries and streams them to smart TVs, streaming boxes and mobile devices. This container is packaged as a standalone Plex Media Server. Straightforward design and bulk actions mean getting things done faster.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/plex-icon.png
  thumbnail: http://the-gadgeteer.com/wp-content/uploads/2015/10/plex-logo-e1446990678679.png
  title:
    en_us: Media
  category: Entertainment
  project_url: https://www.plex.tv/
  port_map: "32400"
  index: /web
