name: domus-photos
services:
  app:
    container_name: domus-photos
    image: photoprism/photoprism:230607
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: "512M"
    network_mode: bridge
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PHOTOPRISM_ADMIN_PASSWORD: "domus"
      PHOTOPRISM_UPLOAD_NSFW: "true"
    volumes:
      - type: bind
        source: /DATA/AppData/photoprism/storage
        target: /photoprism/storage
      - type: bind
        source: /DATA/Media/Gallery
        target: /photoprism/originals
    ports:
      - target: 2342
        published: "2342"
        protocol: tcp
    x-domus:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: TimeZone
        - container: PHOTOPRISM_UPLOAD_NSFW
          defaultValue: true
          description:
            en_us: true or false, is it possible to upload NSFW
        - container: PHOTOPRISM_ADMIN_PASSWORD
          defaultValue: domus
          description:
            en_us: The password of admin
      ports:
        - container: 2342
          description:
            en_us: WebUI HTTP Port
      volumes:
        - container: /photoprism/storage
          description:
            en_us: PhotoPrism storage directory.
        - container: /photoprism/originals
          description:
            en_us: PhotoPrism originals directory.
x-domus:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: PhotoPrism® is an AI-powered app for browsing, organizing & sharing your photo collection. It makes use of the latest technologies to tag and find pictures automatically without getting in your way. You can run it at home, on a private server, or in the cloud.
  tagline:
    en_us: Browsing, organizing & sharing your photo collection
  developer: PhotoPrism
  author: CasaOS Team
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/PhotoPrism/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/PhotoPrism/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/PhotoPrism/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/PhotoPrism/screenshot-3.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/PhotoPrism/thumbnail.png
  tips:
    before_install:
      en_us: |
        Default Account

        | Username | Password |
        | -------- | -------- |
        | `admin`    | `domus`   |
  title:
    en_us: Photos
  category: Entertainment
  project_url: https://www.photoprism.app/
  port_map: "2342"
